name: PbRbSr
channels:
  - conda-forge
dependencies:
  - python=3.10.19
  - jupyterlab
  - notebook
  - ipykernel
  - numpy=2.2.6
  - pandas=2.3.3
  - scipy=1.15.2
  - matplotlib=3.10.9
  - scikit-learn=1.7.2
